//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunPayFR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FunPayMTEntities : DbContext
    {
        public FunPayMTEntities()
            : base("name=FunPayMTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<SupportEmails> SupportEmails { get; set; }
        public virtual DbSet<SupportPhones> SupportPhones { get; set; }
        public virtual DbSet<SupportTeam> SupportTeam { get; set; }
    }
}
